export interface FilterCondition {
  column: string;
  operator?: '=' | '>' | '<' | '>=' | '<=' | 'LIKE' | 'ILIKE' | 'IN';
  value: any;
}

export interface GetRowsOptions {
  filterBy?: FilterCondition[];
  limit?: number;
  offset?: number;
  orderBy?: string;
  orderDirection?: 'ASC' | 'DESC';
}

export interface Column {
  name: string;
  type:
    | 'number'
    | 'boolean'
    | 'datetime'
    | 'date'
    | 'string'
    | 'object'
    | 'Buffer';
  isNullable: false;
  default: string;
  constraints: {
    primaryKey: boolean;
    foreignKey: {
      columnName: string;
      foreignTable: string;
      foreignColumn: string;
    };
  };
  isAutoGenerated: boolean;
}
