import {
  Component,
  EventEmitter,
  Input,
  Output,
  OnChanges,
  SimpleChanges,
  OnInit,
} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Subject } from 'rxjs';
import { DataSource } from 'src/app/models/datasource-config.model';
import { Column } from 'src/app/models/table.model';

@Component({
  selector: 'app-add-row-modal',
  templateUrl: './add-row-modal.component.html',
  styleUrls: ['./add-row-modal.component.css'],
})
export class AddRowModalComponent implements OnInit, OnChanges {
  @Input() sourceType: DataSource;
  @Input() sourceId;
  @Input() showModal = false;
  @Input() editMode = false;
  @Input() selectedItem: any = null;
  @Input() data = {};
  @Input() columns: Column[] = []; // Receive columns from TableEditorComponent
  @Output() closeModalEvent = new EventEmitter<void>();
  @Output() saveItemEvent = new EventEmitter<any>();

  submitted = false;
  form: FormGroup = this.fb.group({});

  /* Foreign Key */
  foreignKeyData: { [key: string]: any[] } = {}; // Store dropdown data
  searchTerms: { [key: string]: string } = {}; // Store search text
  offsets: { [key: string]: number } = {}; // Track pagination offsets
  loading: { [key: string]: boolean } = {}; // Prevent multiple calls
  search$ = new Subject<{ term: any; columnName: string }>();

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.createForm();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.columns && this.columns.length) {
      this.submitted = false;
      this.createForm();
    }
  }

  createForm() {
    let formControls = {};
    this.columns.forEach((col) => {
      if (col.isAutoGenerated) {
        formControls[col.name] = [{ value: '', disabled: true }];
      } else if (col.type === 'object' || col.type === 'Buffer') {
        // For the JSON type column, set a default value and disable the field
        formControls[col.name] = [{ value: '{...}', disabled: true }];
      } else if (col.type === 'datetime' || col.type === 'date') {
        // Convert ISO datetime to "YYYY-MM-DDTHH:MM" format for <input type="datetime-local">
        const isoDate = this.data[col.name] ?? '';
        const formattedDate = isoDate
          ? isoDate.slice(0, col.type === 'datetime' ? 16 : 10)
          : '';
        console.log(formattedDate);

        formControls[col.name] = [
          formattedDate,
          !col.default && !col.isNullable ? Validators.required : [],
        ];
      } else {
        formControls[col.name] = [
          this.data[col.name] ?? '',
          !col.default && !col.isNullable ? Validators.required : [],
        ];
      }
    });
    this.form = this.fb.group(formControls);
  }

  closeModal() {
    this.closeModalEvent.emit();
  }

  saveItem() {
    this.submitted = true;
    if (this.form.invalid) return;
    this.saveItemEvent.emit(this.form);
  }
}
